drop table organization_member 
drop table organization_rank 
drop table quest_reward  
drop table quest_event  
drop table quest  
drop table inventory_item 
drop table inventory  
drop table story_event_character
drop table story_event_location 
drop table story_event_item 
drop table story_event 
drop table item 
drop table relationship 
drop table relationship_type_lookup 
drop table story_character 
drop table story_location 
drop table location_type_lookup 
drop table organization 
drop table alignment_lookup 
drop table character_type 